### PR TITLE
Further UI/UX improvements for commons chat

### PR DESCRIPTION
**Pull request by ajs808**
## Overview

In this PR, we address:
> 2. Currently, the UI design for common chatroom is very rudimentary, and each message is a segment, which looks rather strange.

Instead of having each message be its own separated card, we have each message blend into the chat panel background. Notice that the individual chat cards no longer have a border, and instead the chat container has a border. A user's own messages will still show up with a gray background to differentiate them from messages from other people.
Extends on #30 

[Dokku deployment](https://happycows-ajs808-dev.dokku-04.cs.ucsb.edu/)

## Screenshots (Optional)

Before:
Screenshot 2023-11-27 at 9 47 52 PM

After:
Screenshot 2023-11-28 at 2 39 38 PM

## Feedback Request (Optional)

Please give suggestions on the following:
- How does the UI look?

## Next Steps
- Any further ways to improve the chat UX as described in #15 ? If not, this PR concludes that issue

## Validation (Optional)

1. Download this branch.
2. Run the project.
3. Go to this page.
4. Test this function.

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Addresses #15

### CODE REVIEW

**Review by aditiphatak — DISMISSED** [review]
LGTM!

**Review by pconrad — CHANGES_REQUESTED** [review]
I'm  not sure what you mean by "desegment the chat messages".  And "improve the UI" is a bit vague.

It appears that maybe what you did is to remove the id numbers (which were likely confusing and unnecessary so that's a good change).  Is there anything else we should be noticing?

Being as specific as possible in your PR description will help speed code reviews now and in your future career.

**Comment by ajs808** [comment]
> I'm not sure what you mean by "desegment the chat messages". And "improve the UI" is a bit vague.
> 
> It appears that maybe what you did is to remove the id numbers (which were likely confusing and unnecessary so that's a good change). Is there anything else we should be noticing?
> 
> Being as specific as possible in your PR description will help speed code reviews now and in your future career.

Thanks for the tips, it seemed clear in my head when I wrote the PR but I see how it was unclear now. I updated the description and used new images to make the change more clear.

**Review by pconrad — DISMISSED** [review]
LGTM

**Pull request merged**
