### PR TITLE
Add Last Date field to Commons

### PR DESCRIPTION
**Pull request by katytsao**
## Overview

In this PR, (insert a brief description of what this PR enables for the end user as well as coders. If this placeholder text is still in place, this PR is not yet ready for review).

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

First PR of #11

### CODE REVIEW

**Comment by katytsao** [comment]
waiting to hear back about some questions i had

**Comment by pconrad** [comment]
> waiting to hear back about some questions i had

See: https://ucsb-cs156-f23.slack.com/archives/C065XJGBVL3/p1700722694788749

**Review by ajs808 — DISMISSED** [review]
lgtm!

**Comment by katytsao** [comment]
wondering if i should put this back to draft since it looks like the Report objects also need to have end dates added, since they emulate commons?
(this isn't in the issue specs, just what i've noticed)

**Review by ajs808 — APPROVED** [review]
cool! tested locally, lastDate field is available in list commons, create commons, edit commons, etc. lgtm!

**Review by pconrad — APPROVED** [review]
LGTM.   This would have earned 20 points or more if divided into separate PRs, so I'll give 20 points; it's arguably ok to combine all of these into one PR since the PR focuses on a single issue, and handles all of the concerns for that one issue in the stack from top to bottom.  In fact, some organizations prefer PRs to be constructed like this (they call it a "vertical slice").

**Pull request merged**
